DATE_FORMAT = "%d-%m-%Y"
PROCESSED_TIME_SLOTS = ["0000", "0600", "1200", "1800"]
HUBS_FILE_KEY = "hubs.json"

STATUS_OK = 200
STATUS_BAD_REQUEST = 400
STATUS_NOT_FOUND = 404
STATUS_INTERNAL_SERVER_ERROR = 500

RETRIEVE_RAW_WEATHER_PATH = "/ese/v1/retrieve/raw/weather"
RETRIEVE_PROCESSED_WEATHER_PATH = "/ese/v1/retrieve/processed/weather"